### ISSUE TITLE
Unable to read schema file: Unsupported platform: protoc-3.4.0-linux-x86_64.exe

### ISSUE THREAD

**Issue by otmanel31** [whiver/nifi-protobuf-processor#5]
Hi, 
My protobuf processor works fine for 6 month and brutally after i purged tmp folder, i face an issue:

> 2020-01-29 11:00:01,361 ERROR [Timer-Driven Process Thread-10] c.g.w.nifi.processor.ProtobufDecoder ProtobufDecoder[id=a2ae63e8-1934-3e98-bb0c-55cbe70dfe24] Unable to read schema file: Unsupported platform: protoc-3.4.0-linux-x86_64.exe: com.github.whiver.nifi.exception.SchemaLoadingException: Unable to read schema file: Unsupported platform: protoc-3.4.0-linux-x86_64.exe
com.github.whiver.nifi.exception.SchemaLoadingException: Unable to read schema file: Unsupported platform: protoc-3.4.0-linux-x86_64.exe
        at com.github.whiver.nifi.parser.SchemaParser.parseSchema(SchemaParser.java:73)
        at com.github.whiver.nifi.service.ProtobufService.decodeProtobuf(ProtobufService.java:86)
        at com.github.whiver.nifi.processor.ProtobufDecoder.lambda$0(ProtobufDecoder.java:80)
        at org.apache.nifi.controller.repository.StandardProcessSession.write(StandardProcessSession.java:2887)
        at com.github.whiver.nifi.processor.ProtobufDecoder.onTrigger(ProtobufDecoder.java:75)
        at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
        at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1162)
        at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:209)
        at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:117)
        at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: Unsupported platform: protoc-3.4.0-linux-x86_64.exe
        at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:221)
        at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:182)
        at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:71)
        at com.github.whiver.nifi.parser.SchemaParser.compileProto(SchemaParser.java:46)
        at com.github.whiver.nifi.parser.SchemaParser.parseSchema(SchemaParser.java:58)
        ... 16 common frames omitted

So as understood, a protocjar.webcache folder in /tmp should be not removed, isn't it ?

**Comment by whiver** [comment]
Hi,
I haven't worked on this project for a while, so I'm not super clear on that, but a few thoughts:
- on startup, the processor should download the protoc binaries if not available in the /tmp folder. So indeed, if you cleaned up this folder, it will re-download it.
- so maybe the issue you're facing is due to the newer version that might have been downloaded.
- that's a bit strange that the error comes from protoc-3.4.0-linux-x86_64**.exe** as I guess you're running under Linux right?

I'll try to find time to test it myself and at least update the dependencies. Keep me updated :)

**Comment by otmanel31** [comment]
Hi yes i'm running under linux ... i'll test it in other deployment ...

**Comment by otmanel31** [comment]
i stop and start my nifi server  again today and after starting nifi, i had this error again ... any hints ?

**Comment by ValentinaIvanova** [comment]
Hi!

Got the same error message. Any developments around this issue?

Thanks
Valentina

**Comment by chiko-chan** [comment]
> Hi!
> 
> Got the same error message. Any developments around this issue?
> 
> Thanks
> Valentina

hi， do u fix  this error?

**Comment by chiko-chan** [comment]
> Hi yes i'm running under linux ... i'll test it in other deployment ...

hi, do u fix this error?

**Comment by otmanel31** [comment]
it's a very old issue. If i remember protoc-3.4.0-linux-x86_64.exe that is under tmp folder should not be removed. U can purge every thing else but not this exec. But this is only a quick fix/workaround for me. As i can see, there is no fix for this issue

**Comment by chiko-chan** [comment]
you mean that i should install  it in all node /tmp  ?  when i restart  the nifi cluster and this exec will be deleted again ?

**Comment by otmanel31** [comment]
i don't know, as i worked in standalone environment and not a cluster. For me, if you restart only nifi service, tmp folder content is not deleted. You should have this issue only if you purge manually the tmp folder.

**Comment by hd0124** [comment]
hi @otmanel31 @whiver , its been a long time but I have a question around this if you guys could help.
I am facing this exact issue. My env is airgapped and it does not have access to maven, is there a way to use this processor in such env (since I read that the first time this processor starts it will download stuff from maven)

**Comment by otmanel31** [comment]
Hi @hd0124, i'm not dev or maintener of this lib. It's a time i didn't work with this dependency in a project. i don't understand you question about maven.... You only need maven to build jar and nar files. If your nar is already put in nifi lib folder, you don't need to do anything else. Also, the nar is avaiblable in release page. Where did you see the processor download stuff from maven on start ? it's very strange .... Maven is only a build system to build artifact/exec

**Comment by otmanel31** [comment]
@whiver , as i can see there are update on develop branch. Is there an update about current issue on this branch ?

**Comment by pashtet04** [comment]
Did someone resolve that issue?
